name: Build on PR

on:
  pull_request:

permissions: {}

jobs:
  build-pr:
    uses: ./.github/workflows/docker_build.yml
    permissions:
      contents: read

  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
    permissions:
      contents: read
