name: Build on push to branch

on:
  push:
    branches: [main, ci-staging]

permissions: {}

jobs:
  resolve-qcom-image:
    uses: ./.github/workflows/resolve-qcom-image.yml
    permissions:
      contents: read

  build-daily:
    uses: ./.github/workflows/docker_build.yml
    permissions:
      contents: read
    with:
      create_test_url: true

  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
    permissions:
      contents: read

  test:
    uses: ./.github/workflows/lava-test.yml
    needs: [resolve-qcom-image, build-daily, schema-check]
    permissions:
      actions: read
      checks: write
      contents: read
      packages: read
      pull-requests: write
    secrets:
      LAVATOKEN: ${{ secrets.LAVATOKEN }}
    with:
      build_url: ${{ needs.resolve-qcom-image.outputs.build_url }}
      suite: trixie
