name: Build on push to branch

on:
  push:
    branches: [main, ci-staging]

permissions: {}

jobs:
  resolve-qcom-image-generic:
    uses: ./.github/workflows/resolve-qcom-image.yml
    permissions:
      contents: read
    with:
      source: generic

  resolve-qcom-image-arduino:
    uses: ./.github/workflows/resolve-qcom-image.yml
    permissions:
      contents: read
    with:
      source: arduino

  build-daily:
    uses: ./.github/workflows/docker_build.yml
    permissions:
      contents: read
    with:
      create_test_url: true

  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
    permissions:
      contents: read

  test-generic:
    uses: ./.github/workflows/lava-test.yml
    needs: [resolve-qcom-image-generic, build-daily, schema-check]
    permissions:
      actions: read
      checks: write
      contents: read
      packages: read
      pull-requests: write
    secrets:
      LAVATOKEN: ${{ secrets.LAVATOKEN }}
    with:
      boards_include: '["qrb2210-rb1","qcs6490-rb3gen2-vision-kit"]'
      build_url: ${{ needs.resolve-qcom-image-generic.outputs.build_url }}
      container_digest: ${{ needs.build-daily.outputs.container_digest }}
      qcom_event: ${{ needs.resolve-qcom-image-generic.outputs.event }}
      qcom_ref: ${{ needs.resolve-qcom-image-generic.outputs.ref }}
      qcom_run_attempt: ${{ needs.resolve-qcom-image-generic.outputs.run_attempt }}
      qcom_run_id: ${{ needs.resolve-qcom-image-generic.outputs.run_id }}
      qcom_sha: ${{ needs.resolve-qcom-image-generic.outputs.sha }}
      qcom_workflow: ${{ needs.resolve-qcom-image-generic.outputs.workflow }}
      suite: trixie

  test-arduino:
    uses: ./.github/workflows/lava-test.yml
    needs: [resolve-qcom-image-arduino, build-daily, schema-check]
    permissions:
      actions: read
      checks: write
      contents: read
      packages: read
      pull-requests: write
    secrets:
      LAVATOKEN: ${{ secrets.LAVATOKEN }}
    with:
      boards_include: '["monaco-arduino-monza"]'
      build_url: ${{ needs.resolve-qcom-image-arduino.outputs.build_url }}
      container_digest: ${{ needs.build-daily.outputs.container_digest }}
      qcom_event: ${{ needs.resolve-qcom-image-arduino.outputs.event }}
      qcom_ref: ${{ needs.resolve-qcom-image-arduino.outputs.ref }}
      qcom_run_attempt: ${{ needs.resolve-qcom-image-arduino.outputs.run_attempt }}
      qcom_run_id: ${{ needs.resolve-qcom-image-arduino.outputs.run_id }}
      qcom_sha: ${{ needs.resolve-qcom-image-arduino.outputs.sha }}
      qcom_workflow: ${{ needs.resolve-qcom-image-arduino.outputs.workflow }}
      suite: trixie
