name: Build OCI container images

env:
 BUILD_REFERENCE: ${{ github.head_ref || github.ref_name }} 

on:
  workflow_call:
    outputs:
      artifacts_url:
        description: "URL to retrieve build artifacts"
        value: ${{ jobs.build-debos.outputs.url }}    
  workflow_dispatch:

jobs:
  build:
    name: Build and upload container image(s)
    if: github.repository_owner == 'qualcomm-linux'
    outputs:
      url: ${{ steps.upload_artifacts_s3.outputs.url }}
    runs-on: [ self-hosted, qcom-u2404, arm64 ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
        with:
          persist-credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build OCI tarball
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        push: false
        platforms: linux/arm64
        provenance: mode=max
        tags: aiml-container-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=oci,dest=${{ runner.temp }}/aiml-container-${{ env.BUILD_REFERENCE }}.tar

    - name: Stage OCI artifacts for publishing
      run: |
        set -ux
        # create a directory for the current run
        dir="OCI-artifacts"
        mkdir -v "${dir}"
        cp -v ${{ runner.temp }}/aiml-container-${{ env.BUILD_REFERENCE }}.tar "${dir}"

    - name: Build container and push to registry
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        push: false
        platforms: linux/arm64
        provenance: mode=max
        tags: ghcr.io/qualcomm-linux/aiml-container-test:${{ env.BUILD_REFERENCE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Syft is not packaged in Debian; it's available as a binary tarball or
    # as container image from upstream; it's available on arm64 and x86
    - name: Install Syft
      run: |
        set -ux
        sudo apt -y install curl
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh

    - name: Generate SBOMs with Syft
      run: |
        set -ux
        bin/syft --version
        SYFT_FORMAT_PRETTY=true bin/syft \
            -o cyclonedx-json=container-sbom.cyclonedx.json \
            -o spdx-json=container-sbom.spdx.json \
            -o syft-json=container-sbom.syft.json \
            -o syft-text=container-sbom.syft.txt \
            -o syft-table \
            --parallelism `nproc` \
            --select-catalogers "+dpkg-db-cataloger,+python-package-cataloger" \
            --source-name aiml-container \
            --source-version "${{ env.BUILD_REFERENCE }}" \
            -v \
            OCI-artifacts/aiml-container-${{ env.BUILD_REFERENCE }}.tar

    - name: Stage SBOMs for publishing
      run: |
        set -ux
        gzip container-sbom.*
        dir="sboms"
        mkdir -v sboms
        cp -av container-sbom.*.gz sboms

    - name: Upload SBOMs as private artifacts
      uses: qualcomm-linux/upload-private-artifact-action@aws-v4
      id: upload_sbom_artifacts
      with:
        destination: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.run_id }}-${{ github.run_attempt }}/
        s3_bucket: qcom-prd-gh-artifacts
        path: sboms

    # upload OCI tarnall to a cloud storage space accessible by LAVA and developers
    - name: Upload private artifacts (S3)
      uses: qualcomm-linux/upload-private-artifact-action@aws-v4
      id: upload_artifacts_s3
      with:
        destination: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.run_id }}-${{ github.run_attempt }}/
        s3_bucket: qcom-prd-gh-artifacts
        path: OCI-artifacts

    - name: "Print output"
      env:
        build_url: ${{ steps.upload_artifacts_s3.outputs.url }}
      run: |
        echo "Downloads URL: ${build_url}"
        echo "url=\"${build_url}\"" >> $GITHUB_OUTPUT
        echo "${build_url}" > build_url
        echo "## Download URL" >> $GITHUB_STEP_SUMMARY
        echo "[${build_url}](${build_url})" >> $GITHUB_STEP_SUMMARY
