name: docker build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'qualcomm-linux'
    runs-on: [ self-hosted, qcom-u2404, arm64 ]
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: aiml-container-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
